cargo-features = ["resolver"]

[package]
name = "neovide"
version = "0.7.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"
build = "build.rs"
description = "A simple GUI for Neovim."
resolver = "2"

[workspace]
members = [
    "neovide-derive"
]

[features]
default = []
embed-fonts = []

[dependencies]
neovide-derive = { path = "neovide-derive" }
euclid = "0.20.7"
font-kit = "0.10.0"
skribo = { git = "https://github.com/linebender/skribo" }
lru = "0.4.3"
derive-new = "0.5"
rmpv = "0.4.4"
rust-embed = { version = "5.2.0", features = ["debug-embed"] }
image = "0.22.3"
nvim-rs = { git = "https://github.com/kethku/nvim-rs", features = [ "use_tokio" ] }
tokio = { version = "0.2.9", features = [ "blocking", "process", "time" ] }
async-trait = "0.1.18"
crossfire = "0.1"
lazy_static = "1.4.0"
unicode-segmentation = "1.6.0"
log = "0.4.8"
flexi_logger = { version = "0.14.6", default-features = false }
parking_lot="0.10.0"
cfg-if = "0.1.10"
which = "4"
dirs = "2"
rand = "0.7"
glutin = "0.26"
gl = "0.14.0"

[dev-dependencies]
mockall = "0.7.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[target.'cfg(linux)'.dependencies.skia-safe]
version = "0.37.0"
features = [ "gl", "x11" ]

[target.'cfg(not(linux))'.dependencies.skia-safe]
version = "0.37.0"
features = [ "gl" ]


[profile.release]
debug = true
lto = true
incremental = true

[package.metadata.bundle]
name = "Neovide"
identifier = "com.kethku.neovide"
icon = ["assets/nvim.ico"]
version = "0.6.0"
resources = []
copyright = "Copyright (c) keith 2020. All rights reserved."
category = "Productivity"
short_description = "A simple GUI for Neovim."
long_description = """
This is a simple graphical user interface for Neovim. Where possible there are some graphical improvements, but it should act functionally like the terminal UI.
"""
